config/routes.rb
Rails.application.routes.draw do
  resources :stocks, only: [:index, :create, :destroy]

  root to: 'stocks#index'
end

app/models/stock.rb
class Stock < ActiveRecord::Base
  # validate there is a ticker and that ticker is not in db regardless of its case
  validates :ticker, { presence: true, :uniqueness => { :case_sensitive => false } }

  before_save :uppercase_field  # before saving uppercase all letters

  def uppercase_field
    self.ticker.upcase!
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/stocks_controller.rb
class StocksController < ApplicationController

  def index
    @stocks = Stock.all # list all stocks currently saved in db. call to get data will be made
    @stock = Stock.new  # new stock when user inputs
  end

  def create
    @stock = Stock.new(params_stock)  # save ticker tag to database and upcase all letters

    if @stock.save
      redirect_to stocks_path
    else
      flash[:error] = @stock.errors.full_messages
      redirect_to stocks_path
    end
  end

  def destroy
    Stock.find(params[:id]).destroy
    redirect_to stocks_path
  end

  private

  def params_stock
    params.require(:stock).permit(:ticker)  # whitelist ticker data to save
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/chartkick_helper.rb
module ChartkickHelper
  def chart_options
    { library: { backgroundColor: "#212427", color: "#7CB5EC"} }
  end
end

app/helpers/stocks_helper.rb
module StocksHelper

  # returns stock data for requested stock
  def stock_info(ticker)
    YahooFinance::Client.new.quotes([ticker], info_request)
  end

  # list of all data pieces to retrieve for stock request
  def info_request
    [:name, :symbol, :ask, :change_and_percent_change, :last_trade_date, :days_range,
     :weeks_range_52, :open, :volume, :average_daily_volume, :market_capitalization,
     :pe_ratio, :dividend_per_share, :dividend_yield, :earnings_per_share, :float_shares, :ebitda]
  end

  # returns historical stock data for over a year
  def stock_historical_info(ticker)
    YahooFinance::Client.new.historical_quotes(ticker, { start_date: Date.today - 365, end_date: Date.today })
  end

  # return chart data
  def chart_data(ticker)
    data = stock_historical_info(ticker)
    dates = parse_date(data)
    prices = parse_price(data)
    parse_chart_data(dates, prices)
  end

  # below methods to be used as helpers for the above methods
  # return dates
  def parse_date(stock_data)
    dates = []

    stock_data.each do |date|
      dates << date.trade_date
    end

    return dates
  end

  # return closing stock price
  def parse_price(stock_data)
    prices = []

    stock_data.each do |price|
      prices << price.close
    end

    return prices
  end

  # convert arrays to date => price hash
  def parse_chart_data(dates, prices)
    dates.zip(prices).to_h
  end
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>PaperMillionaire</title>
  <%= stylesheet_link_tag  'application', media: 'all' %>
  <%= javascript_include_tag 'http://www.google.com/jsapi', "chartkick" %>
  <%= javascript_include_tag 'application' %>
  <%= csrf_meta_tags %>
</head>
<body>

<%= yield %>

</body>
</html>

app/views/stocks/_add_stock.html.erb
<%= form_for @stock do |f| %>
  <%= f.text_field :ticker %>
  <%= f.submit "Stock" %>
<% end %>

app/views/stocks/_stock_chart.html.erb
<% data = chart_data(stock.ticker) %>
<%= line_chart data, chart_options %> <!-- need to move options -->

app/views/stocks/_stock_info.html.erb
<% @stocks.each do |stock| %>
  <div class="stock-info row">
    <% data = stock_info(stock.ticker) %>
    <div class="col-md-12">
      <div class="stock-header text-left">
        <span class="delete com-name"> <%= link_to("X", stock_path(stock), method: :delete)  %> </span>
        <strong class="com-name"><%= data[0].name %> (<%= data[0].symbol %>)</strong>
      </div>
    </div>
    <div class="col-md-4">
      <div class="stock-col-1">
        <span><h3 class="quote"><%= data[0].ask %></h3> (<%= data[0].change_and_percent_change %>)</span><br>
        <%= data[0].last_trade_date %>
      </div>
    </div>
    <div class="col-md-4">
      <div class="stock-col-2">
        <span>Range <%= data[0].days_range %></span><br>
        <span>52 week <%= data[0].weeks_range_52 %></span><br>
        <span>Open <%= data[0].open %></span><br>
        <span>Vol/Avg. <%= data[0].volume %>/<%= data[0].average_daily_volume%></span><br>
        <span>Mkt cap <%= data[0].market_capitalization %></span><br>
        <span>P/E <%= data[0].pe_ratio %></span>
      </div>
    </div>
    <div class="col-md-4">
      <div class="stock-col-3">
        <span>Div/yield <%= data[0].dividend_per_share %>/<%= data[0].dividend_yield %></span><br>
        <span>EPS <%= data[0].earnings_per_share %></span><br>
        <span>Shares <%= data[0].float_shares %></span><br>
        <span>EBITDA <%= data[0].ebitda %></span><br>
      </div>
    </div>
     <div class="col-md-12">
      <div class="stock-chart">
        <%= render partial: 'stock_chart', :locals => { :stock => stock } %>  <!-- will display stock chart for ticker -->
      </div>
    </div>
  </div>
<% end %>

app/views/stocks/index.html.erb
<div id="main" class="container">
  <div id="add-stock" class="container text-center">
    <div class="row">
      <div class="col-md-12">
        <%= render 'add_stock' %>    <!--  input bar to add a new stock to the list -->
      </div>
    </div>
  </div>
  <section class="stock container">
    <div class="stock-wrapper row">
      <div class="col-md-6 col-md-offset-3">
        <%= render 'stock_info' %>  <!-- will display stock information for ticker -->
      </div>
    </div>
  </section>
</div>